add fromAddress
dakk/lisk-pool3 pull request #13
Opened 2021-08-29 09:28 UTC by puccca

2021-08-29 20:02 UTC, dakk commented
GJ, please refactor to make it optional (if no fromAddress set, then use delegate address)

2021-08-29 20:12 UTC, puccca commented
Hey! It is optional already. If fromAddress is not set, it will paty from delegate's address (lines 240-241 from liskpool3.py).

2021-08-29 20:28 UTC, dakk requested changes

2021-08-29 20:28 UTC, dakk commented on liskpool3.py
> +	binFromAddress = addressToBinary(conf['fromAddress'])
the check should be done before calling addressToBinary only 
```python
if 'fromAddress' in conf:
   binAddress = ...
````

2021-08-29 20:28 UTC, dakk commented on README.md
> +	"fromAddress": ""					    // Address from where to make the payments. Unchanged if the payments will be made from the delegate's address
// Address from where to make the payments. Remove if the payments will be made from the delegate's address

2021-08-29 20:28 UTC, dakk commented on config.json
> +	"fromAddress": ""
Remove from exaple file; the field should be populated or not present

2021-08-30 13:17 UTC, dakk approved these changes

2021-08-30 13:17 UTC, merged